import { NextResponse } from 'next/server';
import type { NextRequest } from 'next/server';

/**
 * Middleware for URL redirects (WordPress → Next.js)
 *
 * This middleware handles 301 redirects from old WordPress URLs
 * to new Next.js URLs to preserve SEO and prevent broken links.
 *
 * URL mappings are loaded from url-mappings.json (generated by migration scripts)
 */

// URL mappings cache (loaded once on startup)
let urlMappings: Map<string, string> | null = null;

/**
 * Load URL mappings from file or database
 */
async function loadUrlMappings(): Promise<Map<string, string>> {
  if (urlMappings) {
    return urlMappings;
  }

  try {
    // Option 1: Load from static file (for simple redirects)
    // const mappingsPath = path.join(process.cwd(), 'url-mappings.json');
    // if (fs.existsSync(mappingsPath)) {
    //   const data = JSON.parse(fs.readFileSync(mappingsPath, 'utf-8'));
    //   urlMappings = new Map(data.map((m: any) => [m.from, m.to]));
    // }

    // Option 2: Load from database (for dynamic redirects)
    // This would require importing prisma, which may not work in middleware
    // For now, we'll use a fallback approach with common patterns

    // Common WordPress → Next.js URL patterns
    urlMappings = new Map([
      // Add your mappings here, e.g.:
      // ['/old-about-page', '/about'],
      // ['/old-contact', '/contact'],
    ]);

    return urlMappings;
  } catch (error) {
    console.error('Failed to load URL mappings:', error);
    return new Map();
  }
}

/**
 * Generate redirect URL based on patterns
 */
function getRedirectUrl(pathname: string): string | null {
  // Pattern 1: WordPress blog posts
  // Example: /2024/01/15/post-slug/ → /blog/post-slug
  const wpPostPattern = /^\/\d{4}\/\d{2}\/\d{2}\/([^\/]+)\/?$/;
  const wpPostMatch = pathname.match(wpPostPattern);
  if (wpPostMatch) {
    return `/blog/${wpPostMatch[1]}`;
  }

  // Pattern 2: WordPress category archives
  // Example: /category/leadership/ → /blog/category/leadership
  const wpCategoryPattern = /^\/category\/([^\/]+)\/?$/;
  const wpCategoryMatch = pathname.match(wpCategoryPattern);
  if (wpCategoryMatch) {
    return `/blog/category/${wpCategoryMatch[1]}`;
  }

  // Pattern 3: WordPress tag archives
  // Example: /tag/youth/ → /blog/tag/youth
  const wpTagPattern = /^\/tag\/([^\/]+)\/?$/;
  const wpTagMatch = pathname.match(wpTagPattern);
  if (wpTagMatch) {
    return `/blog/tag/${wpTagMatch[1]}`;
  }

  // Pattern 4: WordPress author archives
  // Example: /author/john-doe/ → /blog/author/john-doe
  const wpAuthorPattern = /^\/author\/([^\/]+)\/?$/;
  const wpAuthorMatch = pathname.match(wpAuthorPattern);
  if (wpAuthorMatch) {
    return `/blog/author/${wpAuthorMatch[1]}`;
  }

  // Pattern 5: Remove trailing slashes and redirect
  if (pathname.endsWith('/') && pathname.length > 1) {
    return pathname.slice(0, -1);
  }

  return null;
}

/**
 * Track redirect in database
 */
async function trackRedirect(fromUrl: string, toUrl: string) {
  // TODO: Implement redirect tracking
  // This would update the Redirect model in the database
  // to track hit counts for analytics

  // Example:
  // await prisma.redirect.upsert({
  //   where: { fromUrl },
  //   update: {
  //     hitCount: { increment: 1 },
  //     lastHit: new Date(),
  //   },
  //   create: {
  //     fromUrl,
  //     toUrl,
  //     hitCount: 1,
  //     lastHit: new Date(),
  //   },
  // });
}

export async function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  // Skip middleware for static assets and API routes
  if (
    pathname.startsWith('/_next') ||
    pathname.startsWith('/api') ||
    pathname.startsWith('/static') ||
    pathname.match(/\.(ico|png|jpg|jpeg|gif|svg|webp|css|js|json|xml|txt)$/)
  ) {
    return NextResponse.next();
  }

  // Load URL mappings
  const mappings = await loadUrlMappings();

  // Check for exact match in mappings
  if (mappings.has(pathname)) {
    const redirectTo = mappings.get(pathname)!;
    console.log(`[REDIRECT] ${pathname} → ${redirectTo}`);

    // Track redirect (async, don't wait)
    trackRedirect(pathname, redirectTo).catch(console.error);

    // Return 301 redirect
    const url = request.nextUrl.clone();
    url.pathname = redirectTo;
    return NextResponse.redirect(url, { status: 301 });
  }

  // Check for pattern-based redirects
  const patternRedirect = getRedirectUrl(pathname);
  if (patternRedirect) {
    console.log(`[REDIRECT] ${pathname} → ${patternRedirect} (pattern)`);

    // Track redirect (async, don't wait)
    trackRedirect(pathname, patternRedirect).catch(console.error);

    // Return 301 redirect
    const url = request.nextUrl.clone();
    url.pathname = patternRedirect;
    return NextResponse.redirect(url, { status: 301 });
  }

  // No redirect needed
  return NextResponse.next();
}

// Configure which routes should run the middleware
export const config = {
  matcher: [
    /*
     * Match all request paths except:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * - public files (public directory)
     */
    '/((?!_next/static|_next/image|favicon.ico|.*\\..*|public).*)',
  ],
};
